# .github/workflows/generate_epg.yml

name: Generate Custom EPG

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI
  schedule:
    # Runs every 3 hours at the 40th minute (e.g., 00:40, 03:40, 06:40, etc.)
    - cron: '40 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch all history for git operations
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run EPG Generator Script
      run: python epg_generator.py

    - name: Commit and Push custom_epg.xml
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add custom_epg.xml
        git commit -m "Automated EPG update" || echo "No changes to commit"
        git push
      env:
        # GITHUB_TOKEN is automatically provided by GitHub Actions
        # It has permissions to push to the repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
